### ISSUE TITLE
Address Validation does not seem to work

### ISSUE THREAD

**Issue by ghost** [goshippo/shippo-java-client#23]
I created an invalid address and then called validate on it. It succeeds and does not give any indication of an invalid address even though the underlying API call returns a failure message as documented at https://goshippo.com/docs/reference#addresses-validate

**Comment by mootrichard** [comment]
Would you be able to provide the invalid address that you had used and any logs you have from testing? I want to test it locally to ensure if its a client related issue or an API related issue.
