### ISSUE TITLE
v.1.1.4 .jar files

### ISSUE THREAD

**Issue by timmaybrown** [goshippo/shippo-java-client#5]
Is there a reason there aren't `.jar` files for the `v1.1.4` version but there are for all the other versions of this client?

[https://github.com/goshippo/shippo-java-client/releases/tag/v1.1.4](https://github.com/goshippo/shippo-java-client/releases/tag/v1.1.4)

Thanks!
~Tim

**Comment by assislucas** [comment]
Hi Tim!

We didn't add the `.jar` for v1.1.4 because since most people are adding the library through maven the jar was not useful.
If you really need it I can add it for you, but are you not going to use maven?

Cheers,
Lucas

**Comment by assislucas** [comment]
Well, since you missed it I guess it was somehow helpful for you, so I've added them for v1.1.4.

Let us know if you have more questions,

Thanks!

**Comment by timmaybrown** [comment]
Thanks, I am looking to consume the Java client from within my CFML application. Thanks for the links to the .jars and hopefully I can dig in and expand my understanding of what I need to do dip down to the java layer to leverage the java classes directly from within my CFML code.
